[[redirects]]
  from = "/api/*"
  to = "https://207.180.233.44/api/:splat"
  status = 200
  force = true


[[redirects]]
  from = "/media/*"
  to = "https://207.180.233.44/media/:splat"
  status = 200
  force = true


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200